# Generated by Django 3.0.6 on 2020-05-18 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('author', models.TextField(max_length=32)),
                ('description', models.TextField(blank=True, max_length=512)),
                ('bMethod', models.CharField(choices=[('R', 'Rent'), ('S', 'Sell'), ('B', 'Both')], max_length=1)),
                ('status', models.BooleanField(default=True)),
                ('publication_date', models.DateField(null=True)),
                ('cover', models.URLField(blank=True)),
                ('keyword', models.ManyToManyField(to='bookApp.keywords')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
