# Generated by Django 3.0.6 on 2020-05-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=None, upload_to='covers/'),
        ),
    ]
