# Generated by Django 3.0.6 on 2020-05-18 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookApp', '0002_auto_20200518_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
